import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import showdown from "showdown";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const registryPath = path.join(root, "src/api/registry.json");
const packagePath = path.join(root, "package.json");
const generatedDir = path.join(root, "docs/generated");
const apiDir = path.join(generatedDir, "api");
const manifestPath = path.join(root, "docs/examples/components/catalog.manifest.json");
const srcDir = path.join(root, "src");

const GENERATED_BANNER =
  "<!-- Generated by scripts/generate-docs.mjs. Edit demos.js / registry.json / JSDoc. -->\n\n";

const demosPath = path.join(root, "docs/examples/components/demos.js");
const demosFullPath = path.join(root, "docs/examples/components/demos.full.js");

const docsDir = path.join(root, "docs");
const aiDir = path.join(docsDir, "ai");

const MANUAL_GUIDES = [
  { file: "getting-started.md", title: "Getting started — DrawUI", assetPrefix: "./" },
  { file: "styling.md", title: "Styling — DrawUI", assetPrefix: "./" },
  { file: "publishing.md", title: "Publishing — DrawUI", assetPrefix: "./" },
  { file: "ai/SKILL.md", title: "AI usage guide — DrawUI", assetPrefix: "../" },
];

/** Shared doc-nav links relative to a page's assetPrefix (docs root = "./"). */
function guideNavLinks(assetPrefix) {
  return [
    { href: `${assetPrefix}generated/typedoc/index.html`, label: "TypeDoc" },
    { href: `${assetPrefix}ai/component-index.html`, label: "Component index" },
    { href: `${assetPrefix}ai/SKILL.html`, label: "AI usage guide" },
  ];
}

const markdownConverter = new showdown.Converter({
  tables: true,
  ghCodeBlocks: true,
  strikethrough: true,
  simplifiedAutoLink: true,
  openLinksInNewWindow: false,
});

function rewriteMarkdownLinks(markdown) {
  return markdown.replace(/\]\(([^)]+\.md)(#[^)]*)?\)/g, (_match, file, hash = "") => {
    return `](${file.replace(/\.md$/, ".html")}${hash})`;
  });
}

function markdownToHtml(markdown) {
  const body = markdown.replace(/^<!--[\s\S]*?-->\n\n?/, "");
  return markdownConverter.makeHtml(rewriteMarkdownLinks(body));
}

function renderHtmlDocPage({
  title,
  bodyHtml,
  assetPrefix,
  navLinks = [],
  liveBundle = null,
}) {
  const nav = [
    `<a class="doc-nav-home" href="${assetPrefix}index.html">← drawui docs</a>`,
    ...navLinks.map(
      (link) =>
        `<a href="${link.href}"${link.active ? ' class="is-active"' : ""}>${link.label}</a>`,
    ),
  ].join("\n      ");

  const liveCss = liveBundle ? "drawui.full.css" : "drawui.min.css";
  const liveHead = liveBundle
    ? `
  <script type="importmap">
  {
    "imports": {
      "drawui": "${assetPrefix}dist/${liveBundle}",
      "chart.js/auto": "https://cdn.jsdelivr.net/npm/chart.js@4.4.7/auto/+esm",
      "ag-grid-community": "https://cdn.jsdelivr.net/npm/ag-grid-community@35.2.1/dist/package/main.esm.mjs",
      "jsgantt-improved": "https://cdn.jsdelivr.net/npm/jsgantt-improved@2.8.10/+esm",
      "showdown": "https://cdn.jsdelivr.net/npm/showdown@2.1.0/+esm",
      "@highlightjs/cdn-assets/es/highlight.min.js": "https://cdn.jsdelivr.net/npm/@highlightjs/cdn-assets@11.11.1/es/highlight.min.js"
    }
  }
  </script>`
    : "";

  const liveBody = liveBundle
    ? `
  <script type="module" src="${assetPrefix}api-live.js"></script>`
    : "";

  return `<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <link rel="stylesheet" href="${assetPrefix}dist/${liveCss}">
  <link rel="stylesheet" href="${assetPrefix}styles/themes/dark.css">
  <link rel="stylesheet" href="${assetPrefix}styles/themes/light.css">
  <link rel="stylesheet" href="${assetPrefix}examples/examples.css">
  <link rel="stylesheet" href="${assetPrefix}doc-page.css">${liveHead}
</head>
<body>
  <div class="doc-shell">
    <nav class="doc-nav" aria-label="Documentation">
      ${nav}
    </nav>
    <main class="doc-content Markdown">${bodyHtml}</main>
  </div>${liveBody}
</body>
</html>
`;
}

async function writeMarkdownPage(markdown, mdPath, htmlPath, pageOptions) {
  await mkdir(path.dirname(mdPath), { recursive: true });
  await writeFile(mdPath, markdown, "utf8");
  await writeFile(
    htmlPath,
    renderHtmlDocPage({
      ...pageOptions,
      bodyHtml: markdownToHtml(markdown),
    }),
    "utf8",
  );
}

async function writeGuideHtml(guide) {
  const mdPath = path.join(docsDir, guide.file);
  const htmlPath = path.join(docsDir, guide.file.replace(/\.md$/, ".html"));
  const assetPrefix = guide.assetPrefix ?? "./";
  const markdown = await readFile(mdPath, "utf8");
  await mkdir(path.dirname(htmlPath), { recursive: true });
  await writeFile(
    htmlPath,
    renderHtmlDocPage({
      title: guide.title,
      assetPrefix,
      navLinks: guideNavLinks(assetPrefix),
      bodyHtml: markdownToHtml(markdown),
    }),
    "utf8",
  );
  return htmlPath;
}

const ENTRYPOINT_FILES = {
  drawui: "src/index.js",
};

const STATUS_LABEL = {
  stable: "Stable",
  experimental: "Experimental",
  internal: "Internal",
};

function formatEmits(emits) {
  if (!emits?.length) {
    return "None by default";
  }
  return emits.map((name) => `\`${name}\``).join(", ");
}

function formatEntrypoints(entrypoints) {
  return entrypoints.map((name) => `\`${name}\``).join(", ");
}

function primaryImport(entrypoints) {
  return "drawui";
}

function extractNamedExports(source) {
  const names = new Set();

  for (const match of source.matchAll(/^export\s+(?:async\s+)?(?:class|function)\s+(\w+)/gm)) {
    names.add(match[1]);
  }

  for (const match of source.matchAll(/^export\s+\{\s*([^}]+)\s*\}/gm)) {
    for (const part of match[1].split(",")) {
      const trimmed = part.trim();
      if (!trimmed) continue;
      const alias = trimmed.split(/\s+as\s+/).pop().trim();
      names.add(alias);
    }
  }

  for (const match of source.matchAll(/^export\s+\*\s+from\s+["']([^"']+)["']/gm)) {
    names.add(`*:${match[1]}`);
  }

  return names;
}

async function loadExportSurface(entrypoint, visited = new Set()) {
  const relativePath = ENTRYPOINT_FILES[entrypoint];
  if (!relativePath) {
    throw new Error(`Unknown entrypoint mapping: ${entrypoint}`);
  }

  const absolutePath = path.join(root, relativePath);
  if (visited.has(absolutePath)) {
    return new Set();
  }
  visited.add(absolutePath);

  const source = await readFile(absolutePath, "utf8");
  const names = extractNamedExports(source);

  for (const marker of [...names].filter((name) => name.startsWith("*:"))) {
    names.delete(marker);
    const importPath = marker.slice(2);
    const resolved = path.normalize(
      path.join(path.dirname(absolutePath), importPath.endsWith(".js") ? importPath : `${importPath}.js`),
    );
    const reExported = await loadExportSurfaceFromFile(resolved, visited);
    reExported.forEach((name) => names.add(name));
  }

  if (entrypoint === "drawui") {
    names.add("DrawUI");
    for (const barrel of ["src/exports/shared.js", "src/components/peer/index.js"]) {
      const barrelNames = await loadExportSurfaceFromFile(
        path.join(root, barrel),
        new Set([...visited]),
      );
      barrelNames.forEach((name) => names.add(name));
    }
  }

  return names;
}

async function loadExportSurfaceFromFile(absolutePath, visited) {
  if (visited.has(absolutePath)) {
    return new Set();
  }
  visited.add(absolutePath);

  const source = await readFile(absolutePath, "utf8");
  const names = extractNamedExports(source);

  for (const marker of [...names].filter((name) => name.startsWith("*:"))) {
    names.delete(marker);
    const importPath = marker.slice(2);
    const resolved = path.normalize(
      path.join(path.dirname(absolutePath), importPath.endsWith(".js") ? importPath : `${importPath}.js`),
    );
    const nested = await loadExportSurfaceFromFile(resolved, visited);
    nested.forEach((name) => names.add(name));
  }

  return names;
}

function validateRegistry(registry, exportSurfaces, packageJson) {
  const errors = [];
  const seen = new Set();

  for (const symbol of registry.symbols) {
    if (seen.has(symbol.name)) {
      errors.push(`Duplicate registry symbol: ${symbol.name}`);
      continue;
    }
    seen.add(symbol.name);

    let found = false;
    for (const entrypoint of symbol.entrypoints) {
      const exports = exportSurfaces.get(entrypoint);
      if (!exports) {
        errors.push(`${symbol.name}: unknown entrypoint ${entrypoint}`);
        continue;
      }
      if (exports.has(symbol.name)) {
        found = true;
      }
    }

    if (!found) {
      errors.push(`${symbol.name} is not exported from any listed entrypoint`);
    }
  }

  const publishedCss = Object.keys(packageJson.exports).filter((key) => key.endsWith(".css"));
  for (const css of registry.cssEntryPoints) {
    if (css.status === "internal") continue;
    const exportKey = `./${css.path}`;
    if (!publishedCss.includes(exportKey)) {
      errors.push(`CSS entry ${css.path} is marked ${css.status} but missing from package.json exports`);
    }
  }

  return errors;
}

function collectManifestApis(manifest) {
  const apis = new Set();

  function walkItems(items = []) {
    for (const item of items) {
      for (const api of item.apis ?? []) {
        apis.add(api);
      }
      for (const bucket of [item.siblings, item.alternatives, item.parts, item.variants]) {
        walkItems(bucket);
      }
    }
  }

  for (const category of manifest.categories ?? []) {
    walkItems(category.items);
  }

  for (const category of manifest.peerCategories ?? []) {
    walkItems(category.items);
  }

  if (manifest.peerCategory?.items) {
    walkItems(manifest.peerCategory.items);
  }

  return apis;
}

function manifestApiSymbol(api) {
  if (/^DrawUI\.\w+/.test(api)) {
    return null;
  }

  const ctor = api.match(/^new\s+(\w+)\s*\(/);
  if (ctor) {
    return ctor[1];
  }

  return api.replace(/\(\.\.\.\)$/, "").replace(/\([^)]*\)$/, "").trim().split(/[\s.(]/)[0];
}

function validateManifestApis(manifest, registry) {
  const warnings = [];
  const symbolNames = new Set(registry.symbols.map((symbol) => symbol.name));

  for (const api of collectManifestApis(manifest)) {
    const symbol = manifestApiSymbol(api);
    if (!symbol) {
      continue;
    }

    if (!symbolNames.has(symbol)) {
      warnings.push(`Manifest API "${api}" does not match a registry symbol`);
    }
  }

  return { warnings };
}

/** Section order mirrors src/ layout (primitives, components/*, overlays, workspace). */
/** Hierarchy-aligned sections: Control leaves → Container branches → peers/facade. */
const INDEX_SECTIONS = [
  ["Text", "text"],
  ["Inputs", "inputs"],
  ["Layout", "layout"],
  ["Collections", "collections"],
  ["Panels", "panels"],
  ["Overlays", "overlays"],
  ["Shell", "shell"],
  ["Peers", "peers"],
  ["Facade", "facade"],
];

function renderComponentIndex(registry) {
  const sections = Object.fromEntries(INDEX_SECTIONS.map(([, key]) => [key, []]));

  for (const symbol of registry.symbols) {
    if (!sections[symbol.category]) {
      sections[symbol.category] = [];
    }
    sections[symbol.category].push(symbol);
  }

  let markdown = `${GENERATED_BANNER}# DrawUI.js Component Index

This index documents the maintained public surface of the DrawUI package.
Sections follow the class hierarchy: **Text** and **Inputs** are \`Control\` leaves; **Layout**, **Collections**, **Panels**, **Overlays**, and **Shell** are \`Container\` branches; **Peers** need external packages; **Facade** is the package entry surface.

## Import Surfaces

Use package exports for all public DrawUI consumption:

\`\`\`js
import { DrawUI, FloatingWindow, Button, RadialMenu } from "drawui";
import "drawui/styles/core.css";
\`\`\`

## Status Legend

- **Stable**: documented, maintained package API.
- **Experimental**: public, but behavior or styling may still evolve.
- **Internal**: repository code that should not be treated as package API.

See also the [API reference](../generated/api/index.html) for per-symbol pages.

`;

  for (const [title, key] of INDEX_SECTIONS) {
    const items = sections[key] ?? [];
    if (!items.length) continue;

    markdown += `## ${title}\n\n`;
    markdown += "| Component | Status | Import | Emitted class(es) | Notes |\n";
    markdown += "| --- | --- | --- | --- | --- |\n";

    for (const symbol of items) {
      markdown += `| \`${symbol.name}\` | ${STATUS_LABEL[symbol.status]} | ${formatEntrypoints(symbol.entrypoints)} | ${formatEmits(symbol.emits)} | ${symbol.notes} |\n`;
    }

    markdown += "\n";
  }

  if (registry.factoryNotes?.length) {
    markdown += "### DrawUI Factory Additions\n\n";
    for (const note of registry.factoryNotes) {
      markdown += `- \`${note.api}\` — ${note.notes}\n`;
    }
    markdown += "\n";
  }

  markdown += "## CSS Entry Points\n\n";
  markdown += "| File | Status | Purpose |\n";
  markdown += "| --- | --- | --- |\n";

  for (const css of registry.cssEntryPoints) {
    markdown += `| \`${css.path}\` | ${STATUS_LABEL[css.status]} | ${css.purpose} |\n`;
  }

  markdown += "\n";
  return markdown;
}

function renderApiIndex(registry) {
  let markdown = `${GENERATED_BANNER}# DrawUI API Reference

Generated from \`src/api/registry.json\` and JSDoc in \`src/\`. Manual guides:

- [Getting started](../../getting-started.html)
- [Styling guide](../../styling.html)
- [Publishing](../../publishing.html)
- [Component index](../../ai/component-index.html)
- [AI usage guide](../../ai/SKILL.html)
- [TypeDoc HTML reference](../typedoc/index.html) (DrawUI factories and documented classes)

Per-symbol pages include JSDoc descriptions, \`@example\` snippets, and live previews for examples marked \`// live\`.

## Symbols

| Symbol | Status | Category | Import |
| --- | --- | --- | --- |
`;

  for (const symbol of registry.symbols) {
    markdown += `| [${symbol.name}](./${symbol.name}.html) | ${STATUS_LABEL[symbol.status]} | ${symbol.category} | ${formatEntrypoints(symbol.entrypoints)} |\n`;
  }

  markdown += "\n";
  return markdown;
}

async function listJsFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listJsFiles(full)));
    } else if (entry.isFile() && entry.name.endsWith(".js")) {
      files.push(full);
    }
  }
  return files;
}

function stripStars(commentBody) {
  return commentBody
    .split("\n")
    .map((line) => line.replace(/^\s*\*\s?/, "").replace(/^\s*\*$/, ""))
    .join("\n")
    .trim();
}

function parseExamples(jsdocBody) {
  const examples = [];
  const lines = jsdocBody.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    const exampleMatch = line.match(/^@example(?:\s+(.*))?$/);
    if (!exampleMatch) {
      i += 1;
      continue;
    }

    let caption = "";
    const rest = (exampleMatch[1] || "").trim();
    const captionMatch = rest.match(/^<caption>([\s\S]*?)<\/caption>$/);
    if (captionMatch) {
      caption = captionMatch[1].trim();
    } else if (rest && !rest.startsWith("@")) {
      caption = rest;
    }

    i += 1;
    const bodyLines = [];
    while (i < lines.length && !/^@\w+/.test(lines[i])) {
      bodyLines.push(lines[i]);
      i += 1;
    }

    const rawBody = bodyLines.join("\n").replace(/^\n+/, "").replace(/\n+$/, "");
    if (!rawBody.trim()) continue;

    // Use "// live" (not "// @live") — TypeDoc parses "@live" as a block tag and splits examples.
    const live = /^\s*\/\/\s*live\s*$/m.test(rawBody);
    const code = rawBody
      .replace(/^\s*\/\/\s*live\s*\n?/, "")
      .replace(/\n\s*\/\/\s*live\s*$/m, "")
      .trim();

    examples.push({ caption, code, live });
  }

  return examples;
}

function parseJsdocDescription(jsdocBody) {
  const lines = jsdocBody.split("\n");
  const descLines = [];
  for (const line of lines) {
    if (/^@\w+/.test(line)) break;
    descLines.push(line);
  }
  return descLines.join("\n").trim();
}

function slugify(text, fallback) {
  const slug = String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return slug || fallback;
}

/**
 * Collect class/function-level JSDoc immediately above each declaration.
 * Scans comment+declaration pairs so bodies cannot span earlier blocks.
 * Prefers `export` declarations when the same name appears twice.
 */
function extractAllSymbolJsdocs(source) {
  const found = new Map();
  const normalized = source.replace(/\r\n/g, "\n");
  const pattern =
    /\/\*\*([\s\S]*?)\*\/\s*(export\s+)?(?:async\s+)?(class|function|const)\s+(\w+)/g;

  for (const match of normalized.matchAll(pattern)) {
    const isExport = Boolean(match[2]);
    const name = match[4];
    const body = stripStars(match[1]);
    const parsed = {
      description: parseJsdocDescription(body),
      examples: parseExamples(body),
      isExport,
    };

    if (!parsed.description && !parsed.examples.length) continue;

    const existing = found.get(name);
    if (!existing || (isExport && !existing.isExport)) {
      found.set(name, parsed);
    }
  }

  return found;
}

async function loadAllSymbolDocs() {
  const docs = new Map();
  const files = await listJsFiles(srcDir);

  for (const file of files) {
    const source = await readFile(file, "utf8");
    const fileDocs = extractAllSymbolJsdocs(source);
    const rel = path.relative(root, file).replace(/\\/g, "/");

    for (const [name, parsed] of fileDocs) {
      const existing = docs.get(name);
      const richer =
        existing &&
        parsed.isExport &&
        existing.isExport &&
        (parsed.examples.length > existing.examples.length ||
          (!existing.description && parsed.description));
      if (!existing || (parsed.isExport && !existing.isExport) || richer) {
        docs.set(name, {
          description: parsed.description || existing?.description || "",
          examples:
            parsed.examples.length >= (existing?.examples.length || 0)
              ? parsed.examples
              : existing.examples,
          isExport: parsed.isExport || existing?.isExport || false,
          file: richer || !existing || (parsed.isExport && !existing.isExport)
            ? rel
            : existing.file,
        });
      }
    }
  }

  return docs;
}

function matchBrace(source, openIndex) {
  const open = source[openIndex];
  const close = open === "{" ? "}" : open === "(" ? ")" : "]";
  let depth = 0;
  let quote = null;
  for (let i = openIndex; i < source.length; i += 1) {
    const ch = source[i];
    const prev = source[i - 1];
    if (quote) {
      if (ch === quote && prev !== "\\") quote = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      quote = ch;
      continue;
    }
    if (ch === open) depth += 1;
    else if (ch === close) {
      depth -= 1;
      if (depth === 0) return i;
    }
  }
  return -1;
}

function findExpressionEnd(source, start) {
  let depthParen = 0;
  let depthBrace = 0;
  let depthBracket = 0;
  let quote = null;
  for (let i = start; i < source.length; i += 1) {
    const ch = source[i];
    const prev = source[i - 1];
    if (quote) {
      if (ch === quote && prev !== "\\") quote = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      quote = ch;
      continue;
    }
    if (ch === "(") depthParen += 1;
    else if (ch === ")") depthParen -= 1;
    else if (ch === "{") depthBrace += 1;
    else if (ch === "}") {
      if (depthBrace === 0 && depthParen === 0 && depthBracket === 0) return i;
      depthBrace -= 1;
    } else if (ch === "[") depthBracket += 1;
    else if (ch === "]") depthBracket -= 1;
    else if (
      ch === "," &&
      depthParen === 0 &&
      depthBrace === 0 &&
      depthBracket === 0
    ) {
      return i;
    }
  }
  return source.length;
}

function dedentBlock(body) {
  const lines = body.split("\n");
  const indents = lines
    .filter((line) => line.trim())
    .map((line) => line.match(/^(\s*)/)[1].length);
  const min = indents.length ? Math.min(...indents) : 0;
  return lines.map((line) => line.slice(min)).join("\n").trim();
}

/** Parse `export const NAME = { "id": () => … }` entries into demoId → code body. */
function extractDemoBuilders(source, exportName) {
  const re = new RegExp(`export\\s+const\\s+${exportName}\\s*=\\s*\\{`);
  const match = re.exec(source);
  if (!match) return new Map();

  let i = match.index + match[0].length;
  const map = new Map();

  while (i < source.length) {
    while (i < source.length && /\s/.test(source[i])) i += 1;
    if (source[i] === "}") break;
    if (source[i] === ",") {
      i += 1;
      continue;
    }
    if (source[i] !== '"') break;

    const keyEnd = source.indexOf('"', i + 1);
    const key = source.slice(i + 1, keyEnd);
    i = keyEnd + 1;
    while (i < source.length && (/\s/.test(source[i]) || source[i] === ":")) i += 1;

    const arrow = source.slice(i).match(/^(async\s*)?\(\s*\)\s*=>\s*/);
    if (!arrow) break;
    i += arrow[0].length;

    let body;
    if (source[i] === "{") {
      const end = matchBrace(source, i);
      body = dedentBlock(source.slice(i + 1, end));
      i = end + 1;
    } else {
      const end = findExpressionEnd(source, i);
      const expr = dedentBlock(source.slice(i, end).replace(/,\s*$/, ""));
      body = `return ${expr};`;
      i = end;
    }
    map.set(key, body);
  }

  return map;
}

/** Rewrite gallery namespace style (`DrawUI.X`) to named-import style for API pages. */
function rewriteGalleryCode(code) {
  return code
    .replace(/\bDrawUI\.center\b/g, "center")
    .replace(/\bDrawUI\.ICONS\b/g, "ICONS")
    .replace(/\bDrawUI\.Chart\s*\(/g, "new Chart(")
    .replace(/\bDrawUI\.Spreadsheet\s*\(/g, "new DataGrid(")
    .replace(/\bnew\s+DrawUI\./g, "new ")
    .replace(/\bDrawUI\.(\w+)/g, "$1");
}

function symbolFromApi(api) {
  if (!api) return null;
  let match = api.match(/\bnew\s+(\w+)/);
  if (match) return match[1];
  match = api.match(/\bDrawUI\.(\w+)/);
  if (match) {
    return match[1] === "Spreadsheet" ? "DataGrid" : match[1];
  }
  match = api.match(/^(\w+)\s*\(/);
  if (match) return match[1];
  match = api.match(/^(\w+)$/);
  if (match) return match[1];
  return null;
}

function primarySymbol(apis = [], knownSymbols) {
  const candidates = [];
  for (const api of apis) {
    const name = symbolFromApi(api);
    if (name) candidates.push(name);
  }
  for (const name of candidates) {
    if (knownSymbols.has(name)) return name;
  }
  return candidates[0] || null;
}

function collectManifestDemoBindings(manifest) {
  /** @type {{ demoId: string, caption: string, apis: string[] }[]} */
  const bindings = [];

  function walkItems(items) {
    for (const item of items || []) {
      if (item.demo) {
        bindings.push({
          demoId: item.demo,
          caption: item.title || item.demo,
          apis: item.apis || [],
        });
      }
      for (const sibling of item.siblings || []) {
        if (!sibling.demo) continue;
        bindings.push({
          demoId: sibling.demo,
          caption: sibling.name || item.title || sibling.demo,
          apis: [sibling.api, ...(item.apis || [])].filter(Boolean),
        });
      }
    }
  }

  for (const category of manifest.categories || []) {
    walkItems(category.items);
  }
  for (const category of manifest.peerCategories || []) {
    walkItems(category.items);
  }

  return bindings;
}

function buildGalleryLiveCatalog(manifest, demoBodies, knownSymbols) {
  /** @type {Record<string, { caption: string, code: string, demoId: string }[]>} */
  const catalog = {};
  const missing = [];

  for (const binding of collectManifestDemoBindings(manifest)) {
    const body = demoBodies.get(binding.demoId);
    if (!body) {
      missing.push(binding.demoId);
      continue;
    }
    const symbol = primarySymbol(binding.apis, knownSymbols);
    if (!symbol) continue;
    if (!catalog[symbol]) catalog[symbol] = [];
    catalog[symbol].push({
      caption: binding.caption,
      code: formatExampleCode(rewriteGalleryCode(body)),
      demoId: binding.demoId,
    });
  }

  if (missing.length) {
    console.warn(
      `Warning: manifest demos missing from demos.js / demos.full.js: ${missing.join(", ")}`,
    );
  }

  return catalog;
}

function collectLiveImports(examples, knownSymbols) {
  const used = new Set();
  for (const example of examples) {
    if (!example.live || example.demoId) continue;
    for (const name of knownSymbols) {
      const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const re = new RegExp(`(?:\\bnew\\s+${escaped}\\b|\\b${escaped}\\s*[.(])`);
      if (re.test(example.code)) used.add(name);
    }
  }
  return [...used].sort();
}

function formatExampleCode(body) {
  const lines = body.split("\n");
  if (lines.length < 2) return body;
  const rest = lines.slice(1);
  const indents = rest
    .filter((line) => line.trim())
    .map((line) => line.match(/^(\s*)/)[1].length);
  if (!indents.length) return body;
  const min = Math.min(...indents);
  return [
    lines[0],
    ...rest.map((line) => {
      if (!line.trim()) return "";
      return `  ${line.slice(min)}`;
    }),
  ].join("\n");
}

function renderLiveDemosModule(liveEntries, knownSymbols) {
  const fromGallery = liveEntries.filter((entry) => entry.demoId);
  const fromCode = liveEntries.filter((entry) => !entry.demoId);
  const imports = collectLiveImports(
    fromCode.map((entry) => entry.example),
    knownSymbols,
  );

  let source =
    "/* Generated by scripts/generate-docs.mjs from docs/examples/components/demos*.js (+ JSDoc // live fallbacks). Do not edit. */\n";

  if (fromGallery.length) {
    source += `import { DEMO_BUILDERS } from "../examples/components/demos.js";\n`;
    source += `import { FULL_DEMO_BUILDERS } from "../examples/components/demos.full.js";\n`;
  }

  if (imports.length) {
    source += `import {\n  ${imports.join(",\n  ")},\n} from "drawui";\n`;
  }

  source += `\n`;

  if (fromGallery.length) {
    source += `const BUILDERS = { ...DEMO_BUILDERS, ...FULL_DEMO_BUILDERS };\n\n`;
  }

  source += `export const LIVE_DEMOS = {\n`;

  for (const { id, demoId, example } of liveEntries) {
    if (demoId) {
      source += `  ${JSON.stringify(id)}: () => BUILDERS[${JSON.stringify(demoId)}](),\n`;
      continue;
    }
    const indented = example.code
      .split("\n")
      .map((line) => (line ? `    ${line}` : ""))
      .join("\n");
    source += `  ${JSON.stringify(id)}: () => {\n${indented}\n  },\n`;
  }

  source += `};\n`;
  return source;
}

function assignExampleIds(symbolName, examples) {
  const used = new Set();
  return examples.map((example, index) => {
    let base = slugify(example.caption, example.demoId || String(index));
    let id = `${symbolName}/${base}`;
    let n = 2;
    while (used.has(id)) {
      id = `${symbolName}/${base}-${n}`;
      n += 1;
    }
    used.add(id);
    return { ...example, id };
  });
}

/**
 * Gallery demos are the source of truth when present.
 * Otherwise fall back to JSDoc `@example` blocks (including `// live`).
 */
function mergeLiveCatalog(symbolName, jsdocExamples = [], galleryCatalog = {}) {
  const gallery = (galleryCatalog[symbolName] || []).map((entry) => ({
    caption: entry.caption || "",
    code: entry.code,
    live: true,
    demoId: entry.demoId,
  }));

  if (gallery.length) {
    const nonLive = jsdocExamples.filter((example) => !example.live);
    return [...nonLive, ...gallery];
  }

  return jsdocExamples;
}

function renderSymbolPage(symbol, docs) {
  const importPath = primaryImport(symbol.entrypoints);
  const importStatement =
    importPath === "drawui"
      ? `import { ${symbol.name} } from "drawui";`
      : `import { ${symbol.name} } from "${importPath}";`;

  const description = docs?.description || symbol.notes;
  const examples = docs ? assignExampleIds(symbol.name, docs.examples) : [];

  let markdown = `${GENERATED_BANNER}# ${symbol.name}

**Status:** ${STATUS_LABEL[symbol.status]}  
**Category:** ${symbol.category}  
**Import:** ${formatEntrypoints(symbol.entrypoints)}  
**Emitted class(es):** ${formatEmits(symbol.emits)}

${description}
`;

  if (docs?.file) {
    markdown += `\n_Source: \`${docs.file}\`_\n`;
  }

  markdown += `
## Import

\`\`\`js
${importStatement}
\`\`\`
`;

  if (examples.length) {
    markdown += `\n## Examples\n`;
    for (const example of examples) {
      const heading = example.caption || "Usage";
      markdown += `\n### ${heading}\n\n`;
      markdown += `\`\`\`js\n${example.code}\n\`\`\`\n`;
      if (example.live) {
        markdown += `\n<div class="doc-live-demo" data-live-demo="${example.id}" aria-label="Live preview"></div>\n`;
      }
    }
  }

  markdown += `\n[← Back to API index](./index.html)\n`;
  return { markdown, examples };
}

const registry = JSON.parse(await readFile(registryPath, "utf8"));
const packageJson = JSON.parse(await readFile(packagePath, "utf8"));
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
// Live demos share one module that imports peers (Chart, DataGrid, …),
// so every page with previews must use the full bundle.
const LIVE_BUNDLE = "drawui.full.js";

const exportSurfaces = new Map();
for (const entrypoint of Object.keys(ENTRYPOINT_FILES)) {
  exportSurfaces.set(entrypoint, await loadExportSurface(entrypoint));
}

const errors = validateRegistry(registry, exportSurfaces, packageJson);
if (errors.length) {
  console.error("Registry validation failed:");
  errors.forEach((error) => console.error(`  - ${error}`));
  process.exit(1);
}

const { warnings } = validateManifestApis(manifest, registry);
warnings.forEach((warning) => console.warn(`Warning: ${warning}`));

const symbolNames = registry.symbols.map((symbol) => symbol.name);
const allSymbolDocs = await loadAllSymbolDocs();
const knownSymbols = new Set([
  ...symbolNames,
  ...allSymbolDocs.keys(),
  "DrawUI",
  "ICONS",
  "center",
  "buildWorldFromConfig",
  "createDefaultWorldConfig",
]);

const demoBodies = new Map([
  ...extractDemoBuilders(await readFile(demosPath, "utf8"), "DEMO_BUILDERS"),
  ...extractDemoBuilders(await readFile(demosFullPath, "utf8"), "FULL_DEMO_BUILDERS"),
]);
const galleryCatalog = buildGalleryLiveCatalog(manifest, demoBodies, knownSymbols);

await rm(apiDir, { recursive: true, force: true });
await mkdir(apiDir, { recursive: true });

await mkdir(aiDir, { recursive: true });

const componentIndexMarkdown = renderComponentIndex(registry);
await writeMarkdownPage(
  componentIndexMarkdown,
  path.join(aiDir, "component-index.md"),
  path.join(aiDir, "component-index.html"),
  {
    title: "Component index — DrawUI",
    assetPrefix: "../",
    navLinks: [
      { href: "../generated/typedoc/index.html", label: "TypeDoc" },
      { href: "../generated/api/index.html", label: "API pages" },
      { href: "./SKILL.html", label: "AI usage guide" },
    ],
  },
);

const apiIndexMarkdown = renderApiIndex(registry);
await writeMarkdownPage(
  apiIndexMarkdown,
  path.join(apiDir, "index.md"),
  path.join(apiDir, "index.html"),
  {
    title: "API reference — DrawUI",
    assetPrefix: "../../",
    navLinks: [
      { href: "../typedoc/index.html", label: "TypeDoc" },
      { href: "../../ai/component-index.html", label: "Component index" },
      { href: "../../ai/SKILL.html", label: "AI usage guide" },
    ],
  },
);

const liveEntries = [];
const liveBySymbol = {};
let liveCount = 0;
let exampleCount = 0;
const mergedExamplesBySymbol = new Map();

function recordLiveExamples(name, examples) {
  mergedExamplesBySymbol.set(name, examples);
  exampleCount += examples.length;
  for (const example of examples) {
    if (!example.live) continue;
    liveEntries.push({ id: example.id, demoId: example.demoId, example });
    liveCount += 1;
    if (!liveBySymbol[name]) liveBySymbol[name] = [];
    liveBySymbol[name].push({
      id: example.id,
      caption: example.caption,
      code: example.code,
      demoId: example.demoId || undefined,
    });
  }
}

for (const symbol of registry.symbols) {
  const docs = allSymbolDocs.get(symbol.name) ?? null;
  const merged = mergeLiveCatalog(symbol.name, docs?.examples ?? [], galleryCatalog);
  const examples = assignExampleIds(symbol.name, merged);
  recordLiveExamples(symbol.name, examples);

  const { markdown } = renderSymbolPage(symbol, {
    description: docs?.description || "",
    file: docs?.file,
    examples: merged,
  });

  const needsLive = examples.some((example) => example.live);
  const liveBundle = needsLive ? LIVE_BUNDLE : null;

  await writeMarkdownPage(
    markdown,
    path.join(apiDir, `${symbol.name}.md`),
    path.join(apiDir, `${symbol.name}.html`),
    {
      title: `${symbol.name} — DrawUI API`,
      assetPrefix: "../../",
      liveBundle,
      navLinks: [
        { href: "./index.html", label: "API index", active: true },
        { href: "../typedoc/index.html", label: "TypeDoc" },
        { href: "../../ai/component-index.html", label: "Component index" },
      ],
    },
  );
}

// Non-registry symbols that still have JSDoc / gallery live demos (Badge, Title, …).
for (const name of new Set([...allSymbolDocs.keys(), ...Object.keys(galleryCatalog)])) {
  if (mergedExamplesBySymbol.has(name)) continue;
  const docs = allSymbolDocs.get(name) ?? null;
  const merged = mergeLiveCatalog(name, docs?.examples ?? [], galleryCatalog);
  if (!merged.length) continue;
  recordLiveExamples(name, assignExampleIds(name, merged));
}

await writeFile(
  path.join(generatedDir, "live-demos.js"),
  renderLiveDemosModule(liveEntries, knownSymbols),
  "utf8",
);

await writeFile(
  path.join(generatedDir, "live-demos.json"),
  `${JSON.stringify(liveBySymbol, null, 2)}\n`,
  "utf8",
);

const generatedReadme = `# Generated documentation

This folder is produced by \`npm run docs\`. Do not edit files here by hand.

| Output | Source |
| --- | --- |
| \`api/*.{md,html}\` | \`src/api/registry.json\` + JSDoc in \`src/\` + gallery demos |
| \`live-demos.js\` + \`.json\` | \`docs/examples/components/demos.js\` (+ \`demos.full.js\`) via \`catalog.manifest.json\`; JSDoc \`// live\` only when no gallery demo |
| \`typedoc/\` | JSDoc in \`src/\` (TypeDoc) + live preview injection |
| \`../ai/component-index.*\` | \`src/api/registry.json\` (AI retrieval folder) |
| \`../getting-started.html\`, etc. | Hand-written guides in \`docs/*.md\` |

## Authoring live examples

**One source of truth:** edit \`docs/examples/components/demos.js\` (or \`demos.full.js\` for peers)
and wire the demo id in \`catalog.manifest.json\`. \`npm run docs\` copies those into API /
TypeDoc pages.

For symbols without a gallery demo (helpers, shell notes), add a JSDoc \`@example\` with
\`// live\` on the source declaration:

\`\`\`js
/**
 * @example <caption>Basic</caption>
 * // live
 * return new Disclaimer("See docs/examples/templates.");
 * @category Shell
 */
\`\`\`

To regenerate:

\`\`\`powershell
npm run docs
\`\`\`

Manual documentation lives alongside this folder:

- [Docs hub](../index.html) — TypeDoc, AI Documentation, Developer guides
- [Getting started](../getting-started.html)
- [Styling](../styling.html)
- [Publishing](../publishing.html)
- [AI docs](../ai/) — component index + usage guide
`;

await writeFile(path.join(generatedDir, "README.md"), generatedReadme, "utf8");

for (const guide of MANUAL_GUIDES) {
  await writeGuideHtml(guide);
}

const symbolPages = (await readdir(apiDir)).filter((file) => file.endsWith(".html") && file !== "index.html");

console.log(`Wrote docs/ai/component-index.md + .html`);
console.log(`Wrote docs/generated/api/index.md + .html`);
console.log(`Wrote ${symbolPages.length} symbol pages (.md + .html) under docs/generated/api/`);
console.log(
  `Built ${liveCount} live demos from gallery/JSDoc (${exampleCount} total examples) → docs/generated/live-demos.js`,
);
console.log(`Wrote ${MANUAL_GUIDES.length} guide pages (.html) under docs/`);
